### ISSUE TITLE
Better Routing For Layers

### ISSUE THREAD

**Issue by brendanvinson** [brendanvinson/stormfront-tile-server#5]
As the number of layers we server grows, the current method of 1:1 route:layer will become more cumbersome.

**Comment by ddproxy** [comment]
Although it may take a lot of forethought to construct routes this way...

```yaml
routes:
  hail:
     provider: hail_size
     query: 'select...'
  wind:
     provider: wind_speed
     query: 'select...'
  wwa:
     provider: wwa_things
     query: 'select...'
```
